feat: [sc-31841] Update Transformer to use new UGC Domain
cheddartv/transformer pull request #36
Opened 2024-01-29 13:19 UTC by petro-bishko-sigma

Story details: https://app.shortcut.com/cheddar/story/31841

2024-01-31 13:09 UTC, petro-bishko-sigma commented
@petro-bishko-sigma @zhiln pls review my PR

2024-01-31 14:10 UTC, ignatospadov approved these changes
LGTM @petro-bishko-sigma

2024-04-12 13:23 UTC, ignatospadov requested changes
As discussed, we will need to switch to `ugc.prod.alticeustech.com`

2024-04-12 13:23 UTC, ignatospadov commented on src/mocks/html/editorjs/ampStory.html
> +         src="https://images.ctfassets.net/3kqcuzntcg31/cOpyGRYNloIdLilQw2niR/c18afe600895f0d9cdd7baae1653f21e/a7144bae-12d1-4fcf-bc20-3ff0b9457646.png_width_1200_amp_auto_webp"
shouldnt this be images-cf?

2024-04-12 13:23 UTC, ignatospadov commented on src/mocks/html/editorjs/story.html
> +  <img src="https://images.ctfassets.net/3kqcuzntcg31/cOpyGRYNloIdLilQw2niR/c18afe600895f0d9cdd7baae1653f21e/a7144bae-12d1-4fcf-bc20-3ff0b9457646.png_width_1200_amp_auto_webp" alt=""/>
shouldnt this be images-cf?

2024-04-15 09:55 UTC, petro-bishko-sigma commented on src/mocks/html/editorjs/story.html
> +  <img src="https://images.ctfassets.net/3kqcuzntcg31/cOpyGRYNloIdLilQw2niR/c18afe600895f0d9cdd7baae1653f21e/a7144bae-12d1-4fcf-bc20-3ff0b9457646.png_width_1200_amp_auto_webp" alt=""/>
Url like this https://images-cf.ctfassets.net/3kqcuzntcg31/cOpyGRYNloIdLilQw2niR/c18afe600895f0d9cdd7baae1653f21e/a7144bae-12d1-4fcf-bc20-3ff0b9457646.png_width_1200_amp_auto_webp
doesn't work

2024-04-15 09:56 UTC, petro-bishko-sigma commented on src/mocks/html/editorjs/ampStory.html
> +         src="https://images.ctfassets.net/3kqcuzntcg31/cOpyGRYNloIdLilQw2niR/c18afe600895f0d9cdd7baae1653f21e/a7144bae-12d1-4fcf-bc20-3ff0b9457646.png_width_1200_amp_auto_webp"
Url like this https://images-cf.ctfassets.net/3kqcuzntcg31/cOpyGRYNloIdLilQw2niR/c18afe600895f0d9cdd7baae1653f21e/a7144bae-12d1-4fcf-bc20-3ff0b9457646.png_width_1200_amp_auto_webp
doesn't work

this URL is working: https://images.ctfassets.net/3kqcuzntcg31/cOpyGRYNloIdLilQw2niR/c18afe600895f0d9cdd7baae1653f21e/a7144bae-12d1-4fcf-bc20-3ff0b9457646.png_width_1200_amp_auto_webp

2024-04-15 11:58 UTC, ignatospadov commented on src/mocks/html/editorjs/ampStory.html
> +         src="https://images.ctfassets.net/3kqcuzntcg31/cOpyGRYNloIdLilQw2niR/c18afe600895f0d9cdd7baae1653f21e/a7144bae-12d1-4fcf-bc20-3ff0b9457646.png_width_1200_amp_auto_webp"
https://images-cf.news12static.com/3kqcuzntcg31/cOpyGRYNloIdLilQw2niR/c18afe600895f0d9cdd7baae1653f21e/a7144bae-12d1-4fcf-bc20-3ff0b9457646.png_width_1200_amp_auto_webp

2024-04-15 11:58 UTC, ignatospadov commented on src/mocks/html/editorjs/story.html
> +  <img src="https://images.ctfassets.net/3kqcuzntcg31/cOpyGRYNloIdLilQw2niR/c18afe600895f0d9cdd7baae1653f21e/a7144bae-12d1-4fcf-bc20-3ff0b9457646.png_width_1200_amp_auto_webp" alt=""/>
didnt we switch to using fastly to cache images? @petro-bishko-sigma

2024-04-15 12:03 UTC, petro-bishko-sigma commented on src/mocks/html/editorjs/story.html
> +  <img src="https://images.ctfassets.net/3kqcuzntcg31/cOpyGRYNloIdLilQw2niR/c18afe600895f0d9cdd7baae1653f21e/a7144bae-12d1-4fcf-bc20-3ff0b9457646.png_width_1200_amp_auto_webp" alt=""/>
not sure, I did these chanegs a lot of time ago
should I use https://images-cf.news12static.com instead https://images.ctfassets.net?

2024-04-15 12:31 UTC, ignatospadov commented on src/mocks/html/editorjs/story.html
> +  <img src="https://images.ctfassets.net/3kqcuzntcg31/cOpyGRYNloIdLilQw2niR/c18afe600895f0d9cdd7baae1653f21e/a7144bae-12d1-4fcf-bc20-3ff0b9457646.png_width_1200_amp_auto_webp" alt=""/>
I think so since we are already here anyway @petro-bishko-sigma

2024-04-15 12:32 UTC, petro-bishko-sigma commented on src/mocks/html/editorjs/story.html
> +  <img src="https://images.ctfassets.net/3kqcuzntcg31/cOpyGRYNloIdLilQw2niR/c18afe600895f0d9cdd7baae1653f21e/a7144bae-12d1-4fcf-bc20-3ff0b9457646.png_width_1200_amp_auto_webp" alt=""/>
ok will do
thank you @ignatospadov

2024-06-27 15:10 UTC, ignatospadov approved these changes

2024-06-27 15:11 UTC, merged